### PR TITLE
Clarify README with risk of using a NTLD Domain

### PR DESCRIPTION
**Pull request by gnubytes**
Added one additional bullet point under "Troubleshooting" section based on my experience implementing emailwiz with a New Top-level Domain (NTLD) and sending emails to colleagues at large F500 companies.

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
I don't think the note on new top level domains is really specific to this

The reverse DNS statement at least doesn't seem to be true in my case. My rDNS entries for ipv4 and 6 both go to my main domain without a problem.

On the CNAME note, I think I'd probably just prefer telling people to just use an A record and not drag them through the issues.

**Comment by gnubytes** [comment]
I created two commits too many. Disregard commits on MX records (93b) and Reverse DNS (08c) but my added language around NTLD's in the Troubleshooting section is valid from my experience. It would be good to get that into the documentation, IMO.  Thanks.

**Comment by gnubytes** [comment]
Also, check out intodns.com and query unaboomer.com. It's throwing an error on "MX A Request Returns CNAME". This was the reason I created commit 93b - "MX Records".

**Comment by gnubytes** [comment]
Closing this PR.

**Pull request closed without merging**
